import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "bg-red-500 min-h-screen font-sans antialiased",
        inter.variable
      )}
    >
      <body>
        <Nav></Nav>
        {children}
      </body>
    </html>
  );
}
